In [79]:
import pandas as pd
import numpy as np
import pydot
from IPython.display import Image, display

In [2]:
productions = {}
i = 0
with open("cfg.txt", "r") as f:
    for line in f:   
        line = line.rstrip('\n')
        line = line.replace('\'\'', 'eps')
        line = line.rstrip()
        if line != "":
            productions[i] = line
            i += 1

In [3]:
productions

{0: "START -> S'",
 1: "S' -> S NL S'",
 2: "S' -> eps",
 3: "S -> ID with ( ARGS ) NL S' plant",
 4: 'ARGS -> ARG',
 5: 'ARGS -> ARG , ARGS',
 6: 'ARGS -> eps',
 7: 'ARG -> DTYPE ID',
 8: 'ARG -> DTYPE # ID',
 9: 'S -> FUNCALL',
 10: 'FUNCALL -> reap ID with ( VARS )',
 11: 'VARS -> EXPR',
 12: 'VARS -> EXPR , VARS',
 13: 'VARS -> eps',
 14: 'S -> here lies ID NL __________ NL | NL SS |__________',
 15: 'SS -> | S NL SS',
 16: 'SS -> eps',
 17: 'S -> IFPAIR',
 18: 'IFPAIR -> IFCASE rotten IFPAIR',
 19: 'IFPAIR -> IFCASE rotten NL Sâ€™ dispose',
 20: 'IFPAIR -> IFCASE NL dispose',
 21: 'IFCASE -> EXPR fresh? NL Sâ€™',
 22: 'S -> kill',
 23: 'S -> skip',
 24: 'S -> supply EXPR',
 25: 'S -> sow ASIZE ID of DTYPE',
 26: 'ASIZE -> NUM',
 27: 'ASIZE -> eps',
 28: 'S -> EXPR is EXPR',
 29: 'S -> harvest INIT_COND FINAL_COND STEP BLKARROW NL Sâ€™ sell',
 30: 'INIT_COND -> eps',
 31: 'INIT_COND -> from EXPR is EXPR',
 32: 'FINAL_COND -> eternally',
 33: 'FINAL_COND -> until EXPR',
 34: 'STEP -> eps',
 35: 'STEP -> every EXPR EXPR',
 36: 'S -> engrave EXPR',
 37: 'S -> engrave EXPR on FHANDLE',
 38: 'FHANDLE -> stdout',
 39: 'FHANDLE -> stderr',
 40: 'FHANDLE -> ID',
 41: 'S -> EXPR is gather from stdin',
 42: 'S -> EXPR is gather from EXPR',
 43: 'S -> EXPR is unearth ID LARROW MODE',
 44: 'LARROW -> larr',
 45: 'MODE -> rwb',
 46: 'S -> bury EXPR',
 47: 'DTYPE -> i64',
 48: 'DTYPE -> u64',
 49: 'DTYPE -> f64',
 50: 'DTYPE -> i32',
 51: 'DTYPE -> u32',
 52: 'DTYPE -> f32',
 53: 'DTYPE -> b8',
 54: 'DTYPE -> b1',
 55: 'DTYPE -> c32',
 56: 'DTYPE -> c64',
 57: 'DTYPE -> file',
 58: 'EXPR -> UOP EXPR',
 59: 'EXPR -> [ EXPR ]',
 60: 'EXPR -> [ EXPR ] BOP EXPR',
 61: 'EXPR -> ID',
 62: 'EXPR -> ID BOP EXPR',
 63: 'EXPR -> NUM',
 64: 'EXPR -> NUM BOP EXPR',
 65: 'EXPR -> STR',
 66: 'EXPR -> STR BOP EXPR',
 67: 'EXPR -> FUNCALL',
 68: 'EXPR -> FUNCALL BOP EXPR',
 69: 'UOP -> !',
 70: 'UOP -> ~',
 71: 'BOP -> +',
 72: 'BOP -> -',
 73: 'BOP -> *',
 74: 'BOP -> div',
 75: 'BOP -> /',
 76: 'BOP -> &',
 77: 'BOP -> |',
 78: 'BOP -> ^',
 79: 'BOP -> =',
 80: 'BOP -> #',
 81: 'BOP -> >',
 82: 'BOP -> <',
 83: 'BOP -> arrow',
 84: 'BOP -> ge',
 85: 'BOP -> le',
 86: 'BOP -> ne',
 87: 'BOP -> %',
 88: 'BOP -> &&',
 89: 'BOP -> ||',
 90: 'BOP -> sqrt',
 91: 'NUM -> num',
 92: 'STR -> str',
 93: 'BLKARROW -> end',
 94: 'ID -> id',
 95: 'NL -> nl'}

In [4]:
slr = pd.read_csv('slr.csv')
slr

,State,ACTION,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98,Unnamed: 99,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103
0,NaN,with,(,),plant,",",#,reap,here,lies,...,MODE,DTYPE,EXPR,UOP,BOP,NUM,STR,BLKARROW,ID,NL
1,0.0,NaN,NaN,NaN,r2,NaN,NaN,s16,s5,NaN,...,NaN,NaN,11,18,NaN,20,21,NaN,3,NaN
2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
4,3.0,s28,NaN,r61,NaN,r61,s39,r61,NaN,NaN,...,NaN,NaN,NaN,NaN,29,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,160.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
162,161.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,162
163,162.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164,163.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
165,163.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
slr.columns

Index(['State', 'ACTION', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 94', 'Unnamed: 95', 'Unnamed: 96', 'Unnamed: 97',
       'Unnamed: 98', 'Unnamed: 99', 'Unnamed: 100', 'Unnamed: 101',
       'Unnamed: 102', 'Unnamed: 103'],
      dtype='object', length=104)

In [14]:
goto_index = np.where(slr.columns == 'GOTO')[0][0]
goto_index

78

In [15]:
action_table = slr[slr.columns[:goto_index]]
action_table.columns = ['State'] + list(action_table.iloc[0].values[1:])
action_table = action_table.drop(0, axis=0)
action_table = action_table.astype(str)
action_table = action_table.astype({"State": float})
action_table = action_table.astype({"State": int})
action_table = action_table.set_index('State')
action_table

,with,(,),plant,",",#,reap,here,lies,__________,...,%,&&,||,sqrt,num,str,end,id,nl,$
State,,,,,,,,,,,,,,,,,,,,,
0,nan,nan,nan,r2,nan,nan,s16,s5,nan,nan,...,nan,nan,nan,nan,s24,s25,nan,s15,nan,r2
1,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,acc
2,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,...,nan,nan,nan,nan,nan,nan,nan,nan,s27,nan
3,s28,nan,r61,nan,r61,s39,r61,nan,nan,nan,...,s46,s47,s48,s49,r61,r61,r61,r61,r61,nan
4,nan,nan,r67,nan,r67,s39,r67,nan,nan,nan,...,s46,s47,s48,s49,r67,r67,r67,r67,r9 / r67,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,...,nan,nan,nan,nan,nan,nan,nan,nan,r14,nan
161,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,...,nan,nan,nan,nan,nan,nan,nan,nan,s27,nan
162,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
163,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
163,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan

In [16]:
goto_table = slr[['State'] + list(slr.columns[goto_index:])]
goto_table.columns = ['State'] + list(goto_table.iloc[0].values[1:])
goto_table= goto_table.drop(0, axis=0)
goto_table= goto_table.astype(str)
goto_table= goto_table.astype({"State": float})
goto_table = goto_table.astype({"State": int})
goto_table = goto_table.set_index('State')
goto_table

,START,S',S,ARGS,ARG,FUNCALL,VARS,SS,IFPAIR,IFCASE,...,MODE,DTYPE,EXPR,UOP,BOP,NUM,STR,BLKARROW,ID,NL
State,,,,,,,,,,,,,,,,,,,,,
0,nan,1,2,nan,nan,4,nan,nan,6,17,...,nan,nan,11,18,nan,20,21,nan,3,nan
1,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
2,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,26
3,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,...,nan,nan,nan,nan,29,nan,nan,nan,nan,nan
4,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,...,nan,nan,nan,nan,50,nan,nan,nan,nan,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
161,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,162
162,nan,nan,nan,nan,nan,nan,nan,163,nan,nan,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
163,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
163,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan

In [17]:
class Tree:
    def __init__(self, ide, data, children=[]):
        self.id = ide
        self.data = data
        self.children = children
    
    def add_child(self, node):
        self.children.append(node)

In [18]:
goto_table.loc[92].loc['DTYPE']

'nan'

In [34]:
productions

{0: "START -> S'",
 1: "S' -> S NL S'",
 2: "S' -> eps",
 3: "S -> ID with ( ARGS ) NL S' plant",
 4: 'ARGS -> ARG',
 5: 'ARGS -> ARG , ARGS',
 6: 'ARGS -> eps',
 7: 'ARG -> DTYPE ID',
 8: 'ARG -> DTYPE # ID',
 9: 'S -> FUNCALL',
 10: 'FUNCALL -> reap ID with ( VARS )',
 11: 'VARS -> EXPR',
 12: 'VARS -> EXPR , VARS',
 13: 'VARS -> eps',
 14: 'S -> here lies ID NL __________ NL | NL SS |__________',
 15: 'SS -> | S NL SS',
 16: 'SS -> eps',
 17: 'S -> IFPAIR',
 18: 'IFPAIR -> IFCASE rotten IFPAIR',
 19: 'IFPAIR -> IFCASE rotten NL Sâ€™ dispose',
 20: 'IFPAIR -> IFCASE NL dispose',
 21: 'IFCASE -> EXPR fresh? NL Sâ€™',
 22: 'S -> kill',
 23: 'S -> skip',
 24: 'S -> supply EXPR',
 25: 'S -> sow ASIZE ID of DTYPE',
 26: 'ASIZE -> NUM',
 27: 'ASIZE -> eps',
 28: 'S -> EXPR is EXPR',
 29: 'S -> harvest INIT_COND FINAL_COND STEP BLKARROW NL Sâ€™ sell',
 30: 'INIT_COND -> eps',
 31: 'INIT_COND -> from EXPR is EXPR',
 32: 'FINAL_COND -> eternally',
 33: 'FINAL_COND -> until EXPR',
 34: 'STEP -> eps',
 35: 'STEP -> every EXPR EXPR',
 36: 'S -> engrave EXPR',
 37: 'S -> engrave EXPR on FHANDLE',
 38: 'FHANDLE -> stdout',
 39: 'FHANDLE -> stderr',
 40: 'FHANDLE -> ID',
 41: 'S -> EXPR is gather from stdin',
 42: 'S -> EXPR is gather from EXPR',
 43: 'S -> EXPR is unearth ID LARROW MODE',
 44: 'LARROW -> larr',
 45: 'MODE -> rwb',
 46: 'S -> bury EXPR',
 47: 'DTYPE -> i64',
 48: 'DTYPE -> u64',
 49: 'DTYPE -> f64',
 50: 'DTYPE -> i32',
 51: 'DTYPE -> u32',
 52: 'DTYPE -> f32',
 53: 'DTYPE -> b8',
 54: 'DTYPE -> b1',
 55: 'DTYPE -> c32',
 56: 'DTYPE -> c64',
 57: 'DTYPE -> file',
 58: 'EXPR -> UOP EXPR',
 59: 'EXPR -> [ EXPR ]',
 60: 'EXPR -> [ EXPR ] BOP EXPR',
 61: 'EXPR -> ID',
 62: 'EXPR -> ID BOP EXPR',
 63: 'EXPR -> NUM',
 64: 'EXPR -> NUM BOP EXPR',
 65: 'EXPR -> STR',
 66: 'EXPR -> STR BOP EXPR',
 67: 'EXPR -> FUNCALL',
 68: 'EXPR -> FUNCALL BOP EXPR',
 69: 'UOP -> !',
 70: 'UOP -> ~',
 71: 'BOP -> +',
 72: 'BOP -> -',
 73: 'BOP -> *',
 74: 'BOP -> div',
 75: 'BOP -> /',
 76: 'BOP -> &',
 77: 'BOP -> |',
 78: 'BOP -> ^',
 79: 'BOP -> =',
 80: 'BOP -> #',
 81: 'BOP -> >',
 82: 'BOP -> <',
 83: 'BOP -> arrow',
 84: 'BOP -> ge',
 85: 'BOP -> le',
 86: 'BOP -> ne',
 87: 'BOP -> %',
 88: 'BOP -> &&',
 89: 'BOP -> ||',
 90: 'BOP -> sqrt',
 91: 'NUM -> num',
 92: 'STR -> str',
 93: 'BLKARROW -> end',
 94: 'ID -> id',
 95: 'NL -> nl'}

In [27]:
test_string = 'id is reap id with ( id , id , id ) nl'
test_string1 = 'here lies id nl __________ nl | nl | sow id of i64 nl |__________ nl'

In [58]:
buffer = test_string.split(" ") + ["$"]
stack = ['0']
step = 1
graph_id = 0
action = action_table.loc[0].loc[buffer[0]]
print("Step\tStack\tInput\tAction")
print(step, stack, buffer, action)
while action != "acc":
    if action.startswith('s'):
        stack.append(Tree(graph_id, buffer.pop(0)))
        graph_id += 1
        stack.append(action[1:])
        
    elif action.startswith('r'):
        production = productions[int(action[1:])]
        # Reduce
        lhs, rhs = production.split(' -> ')
        if production.endswith('eps'):
            eps_node = Tree(graph_id, 'eps')
            graph_id += 1
            stack.append(Tree(graph_id, lhs, [eps_node]))
            graph_id += 1
        else:
            children = []
            rhs_stack = rhs.split(' ')
            while(True):
                popped = stack.pop()
                if (isinstance(popped, Tree)):
                    children.append(popped)
                    rhs_stack.pop(0)
                    if not rhs_stack:
                        break
                    
            children.reverse()
            stack.append(Tree(graph_id, lhs, children))
            graph_id += 1
        
        # Go to
        print(stack[-2], stack[-1].data)
        new_state = goto_table.loc[int(stack[-2])].loc[stack[-1].data]
        stack.append(new_state)
   
    action = action_table.loc[int(stack[-1])].loc[buffer[0]]
    step += 1
        
    print(step, stack, buffer, action)

Step	Stack	Input	Action
1 ['0'] ['id', 'is', 'reap', 'id', 'with', '(', 'id', ',', 'id', ',', 'id', ')', 'nl', '$'] s15
2 ['0', <__main__.Tree object at 0x000002147F7F28B0>, '15'] ['is', 'reap', 'id', 'with', '(', 'id', ',', 'id', ',', 'id', ')', 'nl', '$'] r94
0 ID
3 ['0', <__main__.Tree object at 0x000002147F57BBE0>, '3'] ['is', 'reap', 'id', 'with', '(', 'id', ',', 'id', ',', 'id', ')', 'nl', '$'] r61
0 EXPR
4 ['0', <__main__.Tree object at 0x000002147E383460>, '11'] ['is', 'reap', 'id', 'with', '(', 'id', ',', 'id', ',', 'id', ')', 'nl', '$'] s57
5 ['0', <__main__.Tree object at 0x000002147E383460>, '11', <__main__.Tree object at 0x000002147E383490>, '57'] ['reap', 'id', 'with', '(', 'id', ',', 'id', ',', 'id', ')', 'nl', '$'] s16
6 ['0', <__main__.Tree object at 0x000002147E383460>, '11', <__main__.Tree object at 0x000002147E383490>, '57', <__main__.Tree object at 0x000002147E4165B0>, '16'] ['id', 'with', '(', 'id', ',', 'id', ',', 'id', ')', 'nl', '$'] s15
7 ['0', <__main__.Tree object at 0x000002147E383460>, '11', <__main__.Tree object at 0x000002147E383490>, '57', <__main__.Tree object at 0x000002147E4165B0>, '16', <__main__.Tree object at 0x000002147F7F6D90>, '15'] ['with', '(', 'id', ',', 'id', ',', 'id', ')', 'nl', '$'] r94
16 ID
8 ['0', <__main__.Tree object at 0x000002147E383460>, '11', <__main__.Tree object at 0x000002147E383490>, '57', <__main__.Tree object at 0x000002147E4165B0>, '16', <__main__.Tree object at 0x000002147F7F27F0>, '63'] ['with', '(', 'id', ',', 'id', ',', 'id', ')', 'nl', '$'] s85
9 ['0', <__main__.Tree object at 0x000002147E383460>, '11', <__main__.Tree object at 0x000002147E383490>, '57', <__main__.Tree object at 0x000002147E4165B0>, '16', <__main__.Tree object at 0x000002147F7F27F0>, '63', <__main__.Tree object at 0x000002147E383DC0>, '85'] ['(', 'id', ',', 'id', ',', 'id', ')', 'nl', '$'] s120
10 ['0', <__main__.Tree object at 0x000002147E383460>, '11', <__main__.Tree object at 0x000002147E383490>, '57', <__main__.Tree object at 0x000002147E4165B0>, '16', <__main__.Tree object at 0x000002147F7F27F0>, '63', <__main__.Tree object at 0x000002147E383DC0>, '85', <__main__.Tree object at 0x000002147E383220>, '120'] ['id', ',', 'id', ',', 'id', ')', 'nl', '$'] s15
11 ['0', <__main__.Tree object at 0x000002147E383460>, '11', <__main__.Tree object at 0x000002147E383490>, '57', <__main__.Tree object at 0x000002147E4165B0>, '16', <__main__.Tree object at 0x000002147F7F27F0>, '63', <__main__.Tree object at 0x000002147E383DC0>, '85', <__main__.Tree object at 0x000002147E383220>, '120', <__main__.Tree object at 0x000002147E36AE50>, '15'] [',', 'id', ',', 'id', ')', 'nl', '$'] r94
120 ID
12 ['0', <__main__.Tree object at 0x000002147E383460>, '11', <__main__.Tree object at 0x000002147E383490>, '57', <__main__.Tree object at 0x000002147E4165B0>, '16', <__main__.Tree object at 0x000002147F7F27F0>, '63', <__main__.Tree object at 0x000002147E383DC0>, '85', <__main__.Tree object at 0x000002147E383220>, '120', <__main__.Tree object at 0x000002147E383250>, '53'] [',', 'id', ',', 'id', ')', 'nl', '$'] r61
120 EXPR
13 ['0', <__main__.Tree object at 0x000002147E383460>, '11', <__main__.Tree object at 0x000002147E383490>, '57', <__main__.Tree object at 0x000002147E4165B0>, '16', <__main__.Tree object at 0x000002147F7F27F0>, '63', <__main__.Tree object at 0x000002147E383DC0>, '85', <__main__.Tree object at 0x000002147E383220>, '120', <__main__.Tree object at 0x000002147E383280>, '138'] [',', 'id', ',', 'id', ')', 'nl', '$'] s150
14 ['0', <__main__.Tree object at 0x000002147E383460>, '11', <__main__.Tree object at 0x000002147E383490>, '57', <__main__.Tree object at 0x000002147E4165B0>, '16', <__main__.Tree object at 0x000002147F7F27F0>, '63', <__main__.Tree object at 0x000002147E383DC0>, '85', <__main__.Tree object at 0x000002147E383220>, '120', <__main__.Tree object at 0x000002147E383280>, '138', <__main__.Tree object at 0x000002147F7F6E80>, '150'] ['id', ',', 'id', ')', 'nl', '$'] s15
15 ['0', <__main__.Tree object at 0x000002147E383460>, '11', <__main__.Tree object at 0x000002147E383490>, '57', <__main__.Tree object at 0x000002147E4165B0>, '16', <__main__.Tree object at 0x000002147F7F27F0>, '63', <__main__.Tree object at 0x000002147E383DC0>, '85', <__main__.Tree object at 0x000002147E383220>, '120', <__main__.Tree object at 0x000002147E383280>, '138', <__main__.Tree object at 0x000002147F7F6E80>, '150', <__main__.Tree object at 0x000002147E4160D0>, '15'] [',', 'id', ')', 'nl', '$'] r94
150 ID
16 ['0', <__main__.Tree object at 0x000002147E383460>, '11', <__main__.Tree object at 0x000002147E383490>, '57', <__main__.Tree object at 0x000002147E4165B0>, '16', <__main__.Tree object at 0x000002147F7F27F0>, '63', <__main__.Tree object at 0x000002147E383DC0>, '85', <__main__.Tree object at 0x000002147E383220>, '120', <__main__.Tree object at 0x000002147E383280>, '138', <__main__.Tree object at 0x000002147F7F6E80>, '150', <__main__.Tree object at 0x000002147E36ADF0>, '53'] [',', 'id', ')', 'nl', '$'] r61
150 EXPR
17 ['0', <__main__.Tree object at 0x000002147E383460>, '11', <__main__.Tree object at 0x000002147E383490>, '57', <__main__.Tree object at 0x000002147E4165B0>, '16', <__main__.Tree object at 0x000002147F7F27F0>, '63', <__main__.Tree object at 0x000002147E383DC0>, '85', <__main__.Tree object at 0x000002147E383220>, '120', <__main__.Tree object at 0x000002147E383280>, '138', <__main__.Tree object at 0x000002147F7F6E80>, '150', <__main__.Tree object at 0x000002147E3398B0>, '138'] [',', 'id', ')', 'nl', '$'] s150
18 ['0', <__main__.Tree object at 0x000002147E383460>, '11', <__main__.Tree object at 0x000002147E383490>, '57', <__main__.Tree object at 0x000002147E4165B0>, '16', <__main__.Tree object at 0x000002147F7F27F0>, '63', <__main__.Tree object at 0x000002147E383DC0>, '85', <__main__.Tree object at 0x000002147E383220>, '120', <__main__.Tree object at 0x000002147E383280>, '138', <__main__.Tree object at 0x000002147F7F6E80>, '150', <__main__.Tree object at 0x000002147E3398B0>, '138', <__main__.Tree object at 0x000002147E339700>, '150'] ['id', ')', 'nl', '$'] s15
19 ['0', <__main__.Tree object at 0x000002147E383460>, '11', <__main__.Tree object at 0x000002147E383490>, '57', <__main__.Tree object at 0x000002147E4165B0>, '16', <__main__.Tree object at 0x000002147F7F27F0>, '63', <__main__.Tree object at 0x000002147E383DC0>, '85', <__main__.Tree object at 0x000002147E383220>, '120', <__main__.Tree object at 0x000002147E383280>, '138', <__main__.Tree object at 0x000002147F7F6E80>, '150', <__main__.Tree object at 0x000002147E3398B0>, '138', <__main__.Tree object at 0x000002147E339700>, '150', <__main__.Tree object at 0x000002147E36AA00>, '15'] [')', 'nl', '$'] r94
150 ID
20 ['0', <__main__.Tree object at 0x000002147E383460>, '11', <__main__.Tree object at 0x000002147E383490>, '57', <__main__.Tree object at 0x000002147E4165B0>, '16', <__main__.Tree object at 0x000002147F7F27F0>, '63', <__main__.Tree object at 0x000002147E383DC0>, '85', <__main__.Tree object at 0x000002147E383220>, '120', <__main__.Tree object at 0x000002147E383280>, '138', <__main__.Tree object at 0x000002147F7F6E80>, '150', <__main__.Tree object at 0x000002147E3398B0>, '138', <__main__.Tree object at 0x000002147E339700>, '150', <__main__.Tree object at 0x000002147E416400>, '53'] [')', 'nl', '$'] r61
150 EXPR
21 ['0', <__main__.Tree object at 0x000002147E383460>, '11', <__main__.Tree object at 0x000002147E383490>, '57', <__main__.Tree object at 0x000002147E4165B0>, '16', <__main__.Tree object at 0x000002147F7F27F0>, '63', <__main__.Tree object at 0x000002147E383DC0>, '85', <__main__.Tree object at 0x000002147E383220>, '120', <__main__.Tree object at 0x000002147E383280>, '138', <__main__.Tree object at 0x000002147F7F6E80>, '150', <__main__.Tree object at 0x000002147E3398B0>, '138', <__main__.Tree object at 0x000002147E339700>, '150', <__main__.Tree object at 0x000002147F7F6D00>, '138'] [')', 'nl', '$'] r11
150 VARS
22 ['0', <__main__.Tree object at 0x000002147E383460>, '11', <__main__.Tree object at 0x000002147E383490>, '57', <__main__.Tree object at 0x000002147E4165B0>, '16', <__main__.Tree object at 0x000002147F7F27F0>, '63', <__main__.Tree object at 0x000002147E383DC0>, '85', <__main__.Tree object at 0x000002147E383220>, '120', <__main__.Tree object at 0x000002147E383280>, '138', <__main__.Tree object at 0x000002147F7F6E80>, '150', <__main__.Tree object at 0x000002147E3398B0>, '138', <__main__.Tree object at 0x000002147E339700>, '150', <__main__.Tree object at 0x000002147E383AC0>, '154'] [')', 'nl', '$'] r12
150 VARS
23 ['0', <__main__.Tree object at 0x000002147E383460>, '11', <__main__.Tree object at 0x000002147E383490>, '57', <__main__.Tree object at 0x000002147E4165B0>, '16', <__main__.Tree object at 0x000002147F7F27F0>, '63', <__main__.Tree object at 0x000002147E383DC0>, '85', <__main__.Tree object at 0x000002147E383220>, '120', <__main__.Tree object at 0x000002147E383280>, '138', <__main__.Tree object at 0x000002147F7F6E80>, '150', <__main__.Tree object at 0x000002147E32BEB0>, '154'] [')', 'nl', '$'] r12
120 VARS
24 ['0', <__main__.Tree object at 0x000002147E383460>, '11', <__main__.Tree object at 0x000002147E383490>, '57', <__main__.Tree object at 0x000002147E4165B0>, '16', <__main__.Tree object at 0x000002147F7F27F0>, '63', <__main__.Tree object at 0x000002147E383DC0>, '85', <__main__.Tree object at 0x000002147E383220>, '120', <__main__.Tree object at 0x000002147E383BE0>, '137'] [')', 'nl', '$'] s149
25 ['0', <__main__.Tree object at 0x000002147E383460>, '11', <__main__.Tree object at 0x000002147E383490>, '57', <__main__.Tree object at 0x000002147E4165B0>, '16', <__main__.Tree object at 0x000002147F7F27F0>, '63', <__main__.Tree object at 0x000002147E383DC0>, '85', <__main__.Tree object at 0x000002147E383220>, '120', <__main__.Tree object at 0x000002147E383BE0>, '137', <__main__.Tree object at 0x000002147F7F27C0>, '149'] ['nl', '$'] r10
57 FUNCALL
26 ['0', <__main__.Tree object at 0x000002147E383460>, '11', <__main__.Tree object at 0x000002147E383490>, '57', <__main__.Tree object at 0x000002147F7F6DC0>, '54'] ['nl', '$'] r67
57 EXPR
27 ['0', <__main__.Tree object at 0x000002147E383460>, '11', <__main__.Tree object at 0x000002147E383490>, '57', <__main__.Tree object at 0x000002147E36A850>, '76'] ['nl', '$'] r28
0 S
28 ['0', <__main__.Tree object at 0x000002147E3390D0>, '2'] ['nl', '$'] s27
29 ['0', <__main__.Tree object at 0x000002147E3390D0>, '2', <__main__.Tree object at 0x000002147E339280>, '27'] ['$'] r95
2 NL
30 ['0', <__main__.Tree object at 0x000002147E3390D0>, '2', <__main__.Tree object at 0x000002147E339070>, '26'] ['$'] r2
26 S'
31 ['0', <__main__.Tree object at 0x000002147E3390D0>, '2', <__main__.Tree object at 0x000002147E339070>, '26', <__main__.Tree object at 0x000002147F4FE4C0>, '70'] ['$'] r1
0 S'
32 ['0', <__main__.Tree object at 0x000002147F7F2A90>, '1'] ['$'] acc

In [64]:
graph = pydot.Dot("tree")

In [65]:
def dfs(node):
    for child in node.children:
        graph.add_node(pydot.Node(child.id, label=child.data))
        graph.add_edge(pydot.Edge(node.id, child.id))
        
        dfs(child)

In [76]:
stack[1].children[0].children[0].children[0].data

'ID'

In [67]:
graph.add_node(pydot.Node(stack[1].id, label=stack[1].data))
dfs(stack[1])

In [77]:
print(graph)

digraph tree {
31 [label="S'"];
26 [label=S];
31 -> 26;
2 [label=EXPR];
26 -> 2;
1 [label=ID];
2 -> 1;
0 [label=id];
1 -> 0;
3 [label=is];
26 -> 3;
25 [label=EXPR];
26 -> 25;
24 [label=FUNCALL];
25 -> 24;
4 [label=reap];
24 -> 4;
6 [label=ID];
24 -> 6;
5 [label=id];
6 -> 5;
7 [label=with];
24 -> 7;
8 [label="("];
24 -> 8;
22 [label=VARS];
24 -> 22;
11 [label=EXPR];
22 -> 11;
10 [label=ID];
11 -> 10;
9 [label=id];
10 -> 9;
12 [label=,];
22 -> 12;
21 [label=VARS];
22 -> 21;
15 [label=EXPR];
21 -> 15;
14 [label=ID];
15 -> 14;
13 [label=id];
14 -> 13;
16 [label=,];
21 -> 16;
20 [label=VARS];
21 -> 20;
19 [label=EXPR];
20 -> 19;
18 [label=ID];
19 -> 18;
17 [label=id];
18 -> 17;
23 [label=")"];
24 -> 23;
28 [label=NL];
31 -> 28;
27 [label=nl];
28 -> 27;
30 [label="S'"];
31 -> 30;
29 [label=eps];
30 -> 29;
}

In [80]:
plt = Image(graph.create_png())
display(plt)

"dot" with args ['-Tpng', 'C:\\Users\\Pranav\\AppData\\Local\\Temp\\tmpmvlc6tui'] returned code: 1

stdout, stderr:
 b''
b"Error: C:\\Users\\Pranav\\AppData\\Local\\Temp\\tmpmvlc6tui: syntax error in line 35 near ','\r\n"

AssertionError: 1